### ISSUE TITLE
Ipsos

### ISSUE THREAD

**Issue by kiphale** [theNewDynamic/international-criminal-justice-today#55]
I know you are working on lots of other stuff, so I say the following with that knowledge firmly in mind: could we do something to jazz up Ipsos's spot on our main page? It could be something as simple as ability to put one line underneath the title, change the title, and change the layout title of the underneath reports...?

**Comment by budparr** [comment]
Sure thing. I'll circle around to this shortly

**Comment by kiphale** [comment]
Thanks! I just thought if Ipsos was going to do all this extra work, we should hook them up on our website.

**Comment by kiphale** [comment]
Maybe this too...let's discuss what is feasible. 

http://www.international-criminal-justice-today.org/ipsos-polling-data/

**Comment by budparr** [comment]
- [ ] Remove the word "data" from the home page list
- [ ] Highlight the home page stuff better
- [ ] Make slideshow item for Ipsos

**Comment by kiphale** [comment]
By slideshow, I presume you mean the interactive chart that tracks the progress of certain question(s) over successive reports. 

I think "Ipsos Polling Report" sounds best.

**Comment by budparr** [comment]
@kiphale This is the slideshow image I added to the home page.
![ipsos-card-sm-425x445](https://cloud.githubusercontent.com/assets/115347/14794657/2dfc8d1c-0af3-11e6-8db0-8ce3308a43ee.png)
